services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: main-db
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_passwd
    secrets:
      - pg_passwd
    networks:
      - shared
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_passwd
    secrets:
      - minio_passwd
    networks:
      - shared
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
  frontend-web:
    build:
      context: frontend/web
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    networks:
      - shared
    ports:
      - 5173:5173
    volumes:
      - ./frontend/web:/app/web
      - ./frontend/common:/app/common
      - pnpm-cache:/pnpm
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    environment:
      LISTEN_ADDR: 0.0.0.0:5000
    networks:
      - shared
    volumes:
      - ./backend:/app

networks:
  shared:

volumes:
  db-data:
  minio-data:
  pnpm-cache:

secrets:
  pg_passwd:
    file: ./secrets/pg_passwd
  minio_passwd:
    file: ./secrets/minio_passwd
